### ISSUE TITLE
migrate CubeMx problem

### ISSUE THREAD

**Issue by epikao** [chandong83/stm32_i2c_to_usb_hid_multitouch#3]
Hello, if migrate this project to the current CubeMx it changes everything - so the program does not work anymore with, respectively one touch is going to be detected, but it always move from left to right position regardless of the touch position (no multitouch).
Can you update your programm to the current CubeMx?

thanks

**Comment by chandong83** [comment]
Sorry, I can't update to the current cubemx version.
I'm a bit busy these days.

**Comment by epikao** [comment]
ok, for me it is to difficult to port it... I have tried to copy and replace some files but still without success. Do you think you can manage this within the next 2..3 weeks? 

If I don't migrate to current CubeMx it works properly... but even though I hope you can port it to the current CubeMx, that would be very usefull.

thanks

**Comment by swissbyte** [comment]
Hi epikao

I have managed to migrate this project right now. The problem was or is, that the usb hid class file which ST provides, doesnt include the Multitouch device descriptors. These descriptors were added by chandong83. After migrating to a new cubeMX version, these files were automatically replaced by the latest ones. Therefore one must also replace or migrate these two files. 

There is a pull request waiting for approval see #4 
If you are in hurry, you can already clone my own repo. 

Regards

**Comment by chandong83** [comment]
Hi swissbyte

Thank you so much :)

**Comment by chandong83** [comment]
close the issue
